:PROPERTIES:
:ID:       50e0113d-aaeb-419c-a010-f9f973942883
:END:
#+title: A day when a solar flare erupted to reach all planets in it's reach
#+filetags: :dream:
* References
- [[id:9f29e5c2-8fc2-46f2-b906-b7f493ba6f93][Dreams]]

I don't know when this dream started, but the earliest recollection of it is when I noticed that strange colors where coming from outside, I could see the sun in the sky and it was going so fast through it that I just could not believe it; short after there was sort of a fog which would pulse different lights close to the ground and sky, I could see some buildings still but they were surrounded by fog. The fog died down and I could see the starry sky again but this time I saw a ball of flames, the sun and it's eruptions until finally it had a major eruption, as if the sun gained it's own ring; when this eruption reached other planets they suddenly lit up in the sky and I could see them more clearly, I saw Saturn being hit and it's ring being lit up, our planet somehow hadn't been hit or majorly affected by it at that point, though I would imagine an eruption like that would work as a massive EMP and destroy most if not all electronics.
Following this I was in a small field for airplanes to take off of, in which we were on a building close to the runway, I was surrounded by people who knew the eruption would happen that day and wanted to appreciate it, they just didn't know the scale that it would be. There was a small shed in the other side of the building where it seemed like people lived on, there was light coming out and it felt like we, or they, were waiting for someone from there. When the eruption finally happened and the planets were visible they were in awe and realized something: The sun was "testing" the rings of each planet; this led me to have a vision of the surface of the sun, but without it's flames, it was explained that there were two forces fighting each other, two spherical forces that seem to me like atoms now; they were the cause for the eruption and basically control the sun's core via their interaction.
Before we could have a clear sight of these planets, as the sun's eruption hit them a purple glitter-like sea water hit them and covered them, to then unveil the planet that the sun's eruption hit.

I wish I could show what I saw to someone, it was very much realistic but also beautiful; yesterday I watched the first episode of Yofukashi no Uta with Fairy and she kept saying how beautiful the sky and lights were, which I agree, but I would assume that it's what heavily influenced this dream.
