:PROPERTIES:
:ID:       3bb939e5-5291-4d50-8cb8-e9acb29be9c2
:END:
#+title: 2021-09-27
#+filetags: :daily:

* Morning Journal
** What are you grateful for?
Being curious.
** What do you want today's highlight to be?
Be able to properly focus on my tasks.
** What's on your mind?
Not much, just wondering what I gotta do to control my sleep better.
* Tasks [0%]
- [ ] Study
- [ ] Work on Ixtus
* Work hours
| Enter | Lunch         |  Left | Balance |
|-------+---------------+-------+---------|
| 08:01 | 12:23 - 13:35 | 17:06 |  +00:03 |
* Input
* Output
* Evening Reflection
** How are you feeling today?
Relieved, feeling accomplish that I can still do well in first person shooters, but also, not be nervous playing them. Though that is still because I ask too much of myself everytime.
** What could you have done better?
Focus better at work, I was way too tired and I will be tomorrow again since I'm going to sleep late.
** Amazing things that happened
I rocked at FPS! I still have what it takes to do well, I just gotta put in more hours into it.
** What did you learn today?
To learn to let go, sometimes... I have to focus on myself and how I feel, you know, give myself a break.
