:PROPERTIES:
:ID:       6baa7d85-b9fe-4f04-ba87-c419099dd0d8
:END:
#+title: 2022-07-18
#+filetags: :daily:pensative:motivated:

* Input
* Output
* Evening Reflection
** How are you feeling today?
I'm feeling certainly motivated, after all I have accomplished most of what I set myself to do every day on the first day of trying it out... With some hiccups.

I feel like I am in the right path to grow as a human being and to achieve peace of mind, for that, I need to be able to meditate and /remove/ myself from the material around me to the interior, but also the strength to be able to live a healthy life, both physically and psychologically.
** What could you have done better?
I could have woken up earlier, paid attention better to my diligence at work as well to my girlfriend's feelings, I lacked on all these departments today, it feels like I have done a lot but at the same time, little.
** Amazing things that happened
I have finished most of my [[id:04a8eb6a-0f59-4309-a53d-5dfa1d0f47b9][routine]] on the first attempt!
** What did you learn today?
That... My body and mind come first, the rest I can sort through with time. My current job allows me to tackle my issues at work without compromising my issues at life, if my life requires it, work comes second. This does not means that I should give in to wasting more time on my own issues, it just means that I re-allocate that time I should have been working into a different day.
