:PROPERTIES:
:ID:       61efdc88-423f-42d2-a897-f8ca49258a81
:END:
#+title: 2022-11-11
#+filetags: :daily:

* Morning Journal
** What are you grateful for?
The critical thinking that I have, but I need to improve in self control, I know what to do but I have zero willpower to put any of it in practice.
** What do you want today's highlight to be?
I WANT TO BE A LITTLE PRODUCTIVE AT WORK, ANY PRODUCTIVE AND I'LL BE HAPPY.
** What's on your mind?
God I need to work on my willpower, find a solution to my constant sleepiness, it's insane.
* Tasks
** [#C] Contact the company's psychologist
SCHEDULED: [2022-11-11 Fri]
** [#A] Contact the national post office
DEADLINE: [2022-11-11 Fri]
** [#B] Give Hayashi a helping hand
DEADLINE: [2022-11-11 Fri]
** [#A] Finish off the UI side of my current task at work
DEADLINE: [2022-11-11 Fri]
* Input
** [[youtube:07kJ0oidLwU][What every 2K MMR Player Doesn't Understand]]
* Output
* Evening Reflection
** How are you feeling today?
Pumped, my day wasn't productive until towards the end but I feel like I accomplished quite a bit! Helped out Hayashi and friends with the organization of the Mocchitsuke event they're holding tomorrow.
** What could you have done better?
Well... Have actually worked. I just slept, got mad, updated things and never ended up testing what I wrote already.
** Amazing things that happened
Well, Kunen is an One Piece fan! That's absolutely incredible, I would never have thought. Had a great shower when I got home and I felt quite mature.
** What did you learn today?
That Kunen is an One Piece fan, that I like the night life quite a bit and... I feel the most motivated over here. ;)
