:PROPERTIES:
:ID:       e00edea4-757d-4576-8aec-6be896f1e489
:END:
#+title: 2022-06-11
#+filetags: :insight:pensative:daily:

* Morning Journal
** What are you grateful for?
The benefits I have with the company I'm working for, I can safely pay for food to help out my family and so we can eat a little better.
** What do you want the today's highlight to be?
I want to do something productive, have some fun and accomplish something related to Hydractify.
** What's on your mind?
I am glad that I can write these daily notes again, I feel like they'll accompany me along the way for a very, very long time.
* Tasks [1/1]
** KILL Take a look into Minecraft space related mods.
* Input
+ [[https://www.youtube.com/watch?v=QikPqNrlqD0][Ben Chew Discusses Infamous Fist Pump Moment When Amber Heard Mentioned Kate Moss]]
+ [[https://www.youtube.com/watch?v=4SxltbGfRh8][Asmongold finds out he might lose his YouTube Channel]]
+ [[https://pt.wikipedia.org/wiki/Pr%C3%AAmio_Hut%C3%BAz#2003][The song "Eu Nao Pedi Pra Nascer" from the album "Direto do Campo de Extermínio" won the 2003 "Prêmio Hutúz" with album of the year.]]
* Output
* Evening Reflection
** How are you feeling today?
Lost, not sure where to begin with all my problems; I do understand that I can just start from anywhere, and doing anything is better than nothing but the lack of motivation is a huge problem, I don't want to deal with any sort of extra issues at the moment. Quite honestly, I do not really want to do these things, I know that once it gets going I will be motivated but the fact that the surroundings of all of these things are just stressful, it pushes me to not want to do them. I've had problems with my community for a while but lately it couldn't be worse; I am lonely guy but that doesn't means I don't require a level of affection too, I don't get it from anyone, not even my girlfriend. Not always you want to be the big spoon, it's good to be pampered sometimes too.

So generally speaking: I am unmotivated as usual and I am slowly understanding why this is, writing my feelings down is helping already, slowly but surely I will get a grasp on my life once more.
** What could you have done better?
I don't think there is anything I could have done better considering that I was just unmotivated and no one will want to do anything in that state; moreover I have been tired of this loop of putting effort into a project and not receiving the bare minimum back.
** Amazing things that happened
I had really good conversations with my dad and mom today, they were passionate about my note taking tool and I was passionate showing them. Today I also showed my dad a really rough song called [[https://www.youtube.com/watch?v=0x4su2TJQx8]["Eu Nao Pedi Pra Nascer"]], though he hasn't watched it from the beginning to the end just yet, it's just really damn heavy.
** What did you learn today?
That I need therapy and I need to understand already what the hell do I want emotionally, quite honestly.
