:PROPERTIES:
:ID:       803512a8-7e57-4f33-a2cc-d1a141aefb84
:END:
#+title: 2022-06-13
#+filetags: :daily:

* Morning Journal
** What are you grateful for?
Having pursued my passions instead of doing whatever school tried to push towards me; I in a way regret not having focused as much on some topics but the way they were presented at the time made them become really boring and overcomplicated, but they're actually really easy concepts.
** What do you want the today's highlight to be?
I wanna be in bed early this time around, preferably by 23:30 so I can wake up between 06:45 and 07:30. I've been waking up way too late these last 4 weeks and it's not good for me or my position in this job.
** What's on your mind?
Boy, I should've listened to Hip-Hop earlier, because of my early contact with early 2000's American Hip-Hop it kind of stained to me as this style of music which is closer to rap and Brazilian funk, which didn't sound appealing to me; In fact, it isn't that, at least /foreign/ Hip-Hop, I am listening to a lot of Japanese Hip-Hop and man it is really good and entertaining.
* Tasks [2/2]
** DONE Go to the national bank get my recession money from being fired.
** DONE Go to the bank "Banco do Brasil" to figure out if I can't get my salary because the account is blocked, if not, unblock it either way.
* Input
* Output
* Evening Reflection
** How are you feeling today?
** What could you have done better?
** Amazing things that happened
** What did you learn today?
