:PROPERTIES:
:ID:       190fd288-77b9-4ce0-a1d9-ac8f527118a7
:END:
#+title: 2023-05-31
#+filetags: :dream:

* Dream
Elf in corner while we validate that we were staying in a room in that corridor, we interact, says she's there because she's an elf, awkward smile, we  "talk", I see our interaction in my phone, almost like a VN, she explains her situation, things diverge into almost like a sex ad spam "I am a breeding machine", "fuck me daddy" and things of the sort, the screen violently glitches and eventually I come back to reality to see me admitting to the fact that my dream is to one day create a bot based on a lawyer's idea?
Met an Asian lady randomly in a place just like Hercilio Luz, we spoke about LoL, I lied again about rank and gave that whole speech, we started walking together, my "sister" and her friend were in my custody at that moment and they came along to the sidewalk with this Asian lady and her husband, suddenly we are on the side of a train, very scary one too, you have to stay in the wall as below you there's a grid metal floor and then nothing holding you back from being able to just jump off
We leave at the wrong station, we meet up the family in what essentially is the Cathedral in my city, then we head out into the humongous shopping centre that somehow has rooms for us to stay, we walk around it, the place is huge, we eventually are lead into a flight of stairs where multiple people are going through, I somehow get soap in my hands, was about to clean, someone cuts the line and now they have that soap in their hands, they look at me with disgust, I say it's a lotion(? something to smoothen ur skin), people around us notice what I said... Everyone who passes their hand on it start applying it throughout it, I get to the top of the flight of stairs and the floor is filled with soap. We get to a GIANT corridor, everything is so slippery, we can get to the end of it by just sliding, as if you were sliding with socks on in a wooden floor that was just cleaned. We see cars in the way, they're made of acrylic and have that same effect of those small cards where depending on the angle, you can see a differrent image, they look magical, as if they're skipping in some way.
Conversation with elf was a montage, the phone is a means of seeing a resume of what's happening, like a VN. We went through many corridors before getting there, family would follow me every corridor that I said was right, there were 3 of them, we saw many of those acrylic sculptures along the way, where I realised and pointed out they were out of acrylic. We eventually get to the end of the last corridor, I see a sign with the numbers of our rooms, I go into the shady corridor and see a black door, like a stage door, I enter and see a girl holding a list of who's supposed to be in that corridor, I present a card, I guess my card to enter the room? Then I notice an elf in that small room in the corner, who's looking sad.
