:PROPERTIES:
:ID:       09373f8c-02b1-45f7-b75b-67e75030fa89
:END:
#+title: 2023-03-08
#+filetags: :daily:

* Tasks
** DONE Contact Lucas about the task I helped them with Monday and Tuesday.
** DONE Make sure Gabriel reviews my pull request.
** KILL Talk to Gabriel/Pablo about my unopened task.
** DONE Finish quizzes for Gakuen.
* Input
* Output
* Morning Journal
** What are you grateful for?
For my girlfriend's companionship, it has helped me through quite a bit these past months - even if the responses are things I already know a lot of times, it's good to hear it from someone else.
** What do you want today's highlight to be?
Be productive, even if just a little. It has been rough to wake up early and actually contribute to the project, so it would be superb if I were able to do that today. I *specially* want to sleep early today again.
** What's on your mind?
I feel hopeful, I am always at ease when I wake up early. It feels like a good omen but also like my opportunities are broader too, as I will not be as tired so early in the day and will be ready to tackle the night activities with more confidence and less in my head about work, since I should finish the day with the mindset of a "job well done" or something close to it, as I can't when I am working so late.
* Evening Reflection
** How are you feeling today?
Pretty good, I sleep wonderfully and were productive.
** What could you have done better?
Not sure, as much as I have deviated at night and went out to help out with gakuen, it was productive and worthwhile.
** Amazing things that happened
I was unbelievably productive this morning.
** What did you learn today?
That when I wake up early, I am a normal person - in the sense that I can be absurdly productive and motivated. I need to get a healthy sleeping schedule.
