:PROPERTIES:
:ID:       39e8b623-eb15-48c0-8ada-ca288271e0af
:END:
#+title: 2023-01-20
#+filetags: :productive:insight:daily:breakthrough:

* Input
* Output
* Evening Reflection
** How are you feeling today?
Average, not my usual average as of lately so marginally better than usual, I have gained some confidence and ground to stand on, although it's shaky, I can stand atop something again.
** What could you have done better?
Slept earlier the day before so I could wake up earlier today, it messed up my schedule as well as my tasks at work, I ended up working less than I should have... Again, but I was productive enough to feel pretty good about it.
** Amazing things that happened
I have awoken from a nightmare. Years passed by and I just kept shoving, doing what was needed to get by with minimum effort, yet, achieving so much alongside.

Look at it, I have the setup of my dreams: Professional headphones connected through an audio interface, a XLR microphone... 60% keyboard, two monitors floating on arms, a gamer monitor with 144Hz refresh rate, it's FUCKING HUGE! Do you remember when we used that small little monitor to play Battlefield 4? Well, we wrecked people with that shit and here we are, we still wreck people but... Other things took priority after a while. Games are still a huge thing for us but they're more used as a distraction, and due to our stress we can't really deal with competitive games. It isn't like we don't enjoy them anymore, but solo queuing is something that I don't enjoy no more, I would love to though.

HOLY FUCK look what job you have, how much we learned... You are really good at Linux, comparatively anyways. There isn't anything you can't do in it now, research will be needed and some pretty good effort, but, it is so much less than before. You have literally entered a different realm know that you have collected so much knowledge, just gotta work on the lies still... I know it's easy to not face your issues but, we gotta.

It feels strange... As if I am a completely different person, could it be possible that I have split personality? I sure hope not, maybe I was in that state that I do not remember of, where you just do things in automatic so you do not have to deal with it.
** What did you learn today?
That music helps me way too much during work, forget watching videos, clicking things... Listen to music and have fun at work, holy cow how is it fun a lot of times, even if a little mundane at times.

I need to be a little bit more forgiving, I can accomplish so much with a little bit more organizing, I want to keep doing a shit load of things but for that, I need to stop playing so much too and use my knowledge! I will be missing out on a lot if I don't. One step at a time, one day at a time and I will reach the heavens and pierce the stars - to understand the universe I must first learn to co-exist with my troubles.
